#X raise ValueError("classic_warp.find_square_corners: No valid square detected in the image.")
#X raise ValueError("elastix_warp.normalize_for_registration: Cannot normalize image with zero or negative dynamic range.")
# raise RuntimeError("elastix_warp.transformix_point: ITKElastix registration has not been performed yet.")
# raise RuntimeError("elastix_warp.setup_itkelastix_ref_mapping: Install ITKElastix with: pip install itk-elastix")
# raise RuntimeError("elastix_warp.setup_itkelastix_ref_mapping: SIFT-warped reference is empty")
# raise FileNotFoundError(f"pattern_crop.find_pattern_crop: Pattern crop not found for {image_label} {orientation} scan {scan_index}. Checked candidates: {candidates}")
# raise ValueError("pattern_crop.show_pattern_classification_results: No evaluated crops to display.")
#X raise ValueError("sift_warp.sift_homography_with_origin: image1 and image2 must not be None")
#X raise ValueError("sift_warp.sift_homography_with_origin: pixels_per_unit_x and pixels_per_unit_y must be > 0")
#X raise RuntimeError("sift_warp.sift_homography_with_origin: OpenCV SIFT is unavailable in this build (missing cv2.SIFT_create)")
#X raise RuntimeError("sift_warp.sift_homography_with_origin: Failed to extract SIFT descriptors from one or both images")
#X raise RuntimeError(f"sift_warp.sift_homography_with_origin: Not enough good SIFT matches ({len(good_matches)}), need at least {min_match_count}")
#X raise RuntimeError("sift_warp.sift_homography_with_origin: Failed to estimate homography from SIFT correspondences")
# raise ValueError("yolo_model.count_4pts_pattern: Input image is None")
# raise RuntimeError(f"yolo_model.count_4pts_pattern: Error loading model from {PT4_MODEL_PATH}: {e}")
# raise RuntimeError("yolo_model.count_4pts_pattern: YOLO returned no results")
# raise RuntimeError("yolo_model.count_4pts_pattern: YOLO returned no bounding boxes")
# raise FileNotFoundError(f"yolo_model.extract_yolo_detections: Could not read image: {curr_image}")
# raise ValueError("yolo_model.extract_yolo_detections: Invalid image array")
# raise ValueError("yolo_model.visualize_detections: No detections to visualize")
# raise RuntimeError(f"usaf_algo.coordinate_calibration: Failed to load SIFT reference image: {C.SIFT_REF_IMAGE_PATH}")
#X raise ValueError("usaf_algo.calculate_focus_scores: Input image is None.")
# raise ValueError("usaf_algo.calculate_focus_scores: Failed to find valid square after 3 attempts")
#X raise ValueError("usaf_algo.calculate_focus_scores: Large angles difference detected")
# raise ValueError("usaf_algo.find_best_focus_group: scores_list is None")
# raise ValueError(f"usaf_algo.find_usaf_score: Failed to read image from {image_path}")
#X raise ValueError("usaf_algo.find_usaf_score: The image is too blurry for detection")
#X raise ValueError("usaf_algo.find_usaf_score: No best focus group found after all attempts")
#X raise ValueError("usaf_algo.calculate_focus_scores: scanline grid misalignment detected")